version: '3.1'
services:
  web:
    build: .
    container_name: blog
    command: python -u run.py
    # command: python -u -m gunicorn --bind 0.0.0.0:5000 run:app
    ports:
      - "5000:5000"
    
    expose:
      - "5000"

    volumes:
      - .:/app
    
    links:
      - db
    
    network_mode: host

    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=
      - FLASK_RUN_PORT=5000
      - FLASK_RUN_CERT=adhoc
      - FLASK_RUN_KEY=adhoc
      - FLASK_RUN_NO_RELOAD=0
      

  db:
    image: mongo:latest
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=blog
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass

  nginx:
    build: ./nginx
    environment:
      - SERVER_NAME=0.0.0.0
    ports:
      - 1337:80
    depends_on:
      - web
    restart: always
    network_mode: host